stages:
  - build

build:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage:
    - build
  script:
    - /kaniko/executor 
        --context . 
        --dockerfile Dockerfile 
        --destination ${CI_REGISTRY_IMAGE}/gpe:latest