{
 "title": "GitLab Pages",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(gpe_check_running,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Check Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpe_last_check_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Check State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpe_check_running{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total Projects",
   "type": "stat",
   "description": "Number of projects which were checked",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpe_projects_checked_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # Deployed Pages",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpe_project_pages_enabled{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gpe_projects_checked_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # Custom Domains",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(gpe_custom_domains_verified{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gpe_project_pages_enabled{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpe_last_check_run_finished_seconds{instance=~\"$instance\"} * 1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Next Check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpe_next_check_run_scheduled_seconds{instance=~\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Checks",
   "type": "stat",
   "description": "Number of projects which failed the pages check",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(gpe_project_pages_enabled{check_status=\"failed\", instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # Deployed Pages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(gpe_project_pages_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # Custom Domains",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(gpe_custom_domains_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Projects with Custom Domains",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "gpe_project_pages_enabled{instance=~\"$instance\"} == 1",
     "legendFormat": "{{ project_id }}"
    },
    {
     "expr": "gpe_custom_domains_verified{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Projects with Pages",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "gpe_project_pages_enabled{instance=~\"$instance\"} == 1",
     "legendFormat": "{{ project_id }}"
    }
   ]
  }
 ]
}