name: Build Exporter Docker Images

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GO_VERSION: '1.21'


jobs:

  build-dockerimages:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      
      - name: Set Image Tag
        run: |
          if [[ ${{ env.GITHUB_REF_NAME }} == "main" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          elif [[ ${{ env.GITHUB_REF_NAME }} =~ ^[0-9]+(\.[0-9]+)*$ ]]; then
            echo "IMAGE_TAG=${{ env.GITHUB_REF_NAME }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          load: true
          file: ${{ github.workspace }}/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
          build-args: |
            GPE_VERSION=test

      - name: Test
        run: |
          docker run --rm \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test -v

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          build-args: |
            GPE_VERSION=${{ env.IMAGE_TAG }}